version: '3.8'

services:
  web:
    build: .
    restart: always
    environment:
      TZ: "Europe/Istanbul"
    command: python manage.py runserver 0.0.0.0:8015
    networks:
      docker_network_custom:
        ipv4_address: 172.19.1.1
    volumes:
      - .:/usr/app/
    ports:
      - 8015:8015
  celery:
    build: .
    restart: always
    environment:
      TZ: "Europe/Istanbul"
    command: celery -A config worker --loglevel=INFO --concurrency=10 -n worker_dokr2
    networks:
      docker_network_custom:
        ipv4_address: 172.19.1.2
    volumes:
      - .:/usr/app/
  celery-beat:
    build: .
    restart: always
    environment:
      TZ: "Europe/Istanbul"
    command: celery -A config beat --loglevel=INFO
    networks:
      docker_network_custom:
        ipv4_address: 172.19.1.3
    volumes:
      - .:/usr/app/

networks:
  docker_network_custom:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
